//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom8_QLTV.src.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryManagementEntities : DbContext
    {
        public libraryManagementEntities()
            : base("name=libraryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book_borrow> book_borrow { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<borrow> borrows { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<category_book> category_book { get; set; }
        public virtual DbSet<permission_role> permission_role { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<reader> readers { get; set; }
        public virtual DbSet<role_user> role_user { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
