//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom8_QLTV.src.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission_role
    {
        public long id { get; set; }
        public long permission_id { get; set; }
        public long role_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual permission permission { get; set; }
        public virtual role role { get; set; }
    }
}
